name: Move assigned Issues to the In Progress column

on: 
  issues:
    types: [assigned]

jobs:
  mark-assigned-issues-inprogress:
    runs-on: ubuntu-latest
    
    steps:
      - name: move-assigned-issue-to-in_progress-column
        uses: takanabe/github-actions-automate-projects@v0.0.2
        if: github.event_name == 'issues' && github.event.action == 'assigned'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PROJECT_URL: https://github.com/orgs/enBloc-org/projects/4/
          GITHUB_PROJECT_COLUMN_NAME: In Progress